### ISSUE TITLE
Initial ToDo's

### ISSUE THREAD

**Issue by eabase** [AntiCoV/RaC#1]
Add an initial list of issues and things to do. 

 - [ ] Improve the README with relevant details.
 - [ ] Add URL's to different data _sources_ and data _sets_. 
 - [ ] Ensure we have a list of literature References for papers discussed
 -  [ ] Add a tools folder where we keep language specific programs or scripts 
 - [ ] Add licensing to this repo and to relevant code. (If you write own code, please include/indicate what license you want it to have.)
 
---

Any other ideas?
